directories:
  output: /Users/konstantinos/Dev/Projects/Ipsosboard/.desktop-installer
  buildResources: build
  app: /Users/konstantinos/Dev/Projects/Ipsosboard/.meteor/desktop-build
icon: .desktop/assets/meteor.ico
appId: meteor.app
productName: My Meteor App
compression: maximum
win:
  target: nsis
squirrelWindows:
  iconUrl: 'https://github.com/wojtkowiak/meteor-desktop/blob/beta/scaffold/assets/meteor.ico?raw=true'
  loadingGif: .desktop/assets/loading.gif
publish:
  - provider: generic
    url: 'http://127.0.0.1:8080/'
mac:
  icon: .desktop/assets/meteor.icns
dmg:
  icon: .desktop/assets/meteor.icns
  background: .desktop/assets/dmgBackground.png
  iconSize: 54
  contents:
    - x: 377
      'y': 190
      type: link
      path: /Applications
    - x: 63
      'y': 190
      type: file
  window:
    width: 480
    height: 300
asar: false
npmRebuild: true
electronVersion: 2.0.10
